---
- name: Stop and disable collectd service
  ansible.builtin.service:
    name: collectd
    state: stopped
    enabled: no
  become: true

- name: Uninstall collectd and collectd-write_prometheus plugin
  package:
    name:
      - collectd
      - collectd-write_prometheus
    state: absent
    purge: yes
  become: true
  

- name: Delete collectd configuration files
  file:
    path: /etc/collectd
    state: absent
    recurse: yes
  become: true